# Variable setup.
- name: Include OS-Specific variables
  include_vars: "{{ ansible_os_family }}.yml"
 

- name: Define host_ip
  set_fact:
    host_ip: "{{ __host_ip }}"
  when: host_ip is not defined

- include: install.yml