# Variable setup.
- name: Include OS-Specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: [nexus]

  
- name: Define host_ip
  set_fact:
    host_ip: "{{ __host_ip }}"
  when: host_ip is not defined
  tags: [nexus]

- name: nexus Data dirctory are created
  file: path=/data/nexus-data/ state=directory mode=0755
  ignore_errors: yes
  tags: [nexus]
 
 

- name: nexus Container is running
  docker_container:
    privileged: yes
    env:
      JAVA_OPTS: "  -Duser.timezone=Asia/Taipei -server  -Djava.net.preferIPv4Stack=true"
      JAVA_MAX_HEAP: 1500m
      JAVA_MIN_HEAP: 1500m   
    name: nexus
    image: "sonatype/nexus3:{{ nexus_version }}"     
    ports: 
     - "8080:8081" 
    volumes: 
      - /data/nexus-data:/sonatype-work:Z
  register: container_result
  tags: [nexus]
  #ref: https://github.com/OpenShiftDemos/nexus/issues/5

  
