# - name:  set-timezone Asia/Taipei
#   shell: timedatectl set-timezone Asia/Taipei
#   ignore_errors: yes
#   tags:  [common]

# - name:  Extra Packages for Enterprise Linux (or EPEL) is present
#   yum: 
#      name: epel-release 
#      state: latest  
#   ignore_errors: yes
#   tags: [common]

- name: CentOS files are copied
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ centos_files }}"
  tags: [common]


- name: selenix  policycoreutils
  yum: name=policycoreutils-python state=latest
  tags: [common]

- name: selenix policies
  shell: semanage port -a -t mysqld_port_t -p tcp {{ item }}
  with_items:
    - 24901
    - 24902
    - 24903
    - 24904
  ignore_errors: yes
  tags: [common]

- name: firewalld  policies
  shell:  firewall-cmd --zone=public --add-port={{ item }}/tcp --permanent
  with_items:
    - 24901
    - 24902
    - 24903
    - 24904
    - 3306
  ignore_errors: yes
  tags: [common]


- name: CentOS Daemon is reloaded
  command: systemctl daemon-reload
  tags: [common]

- name: Centos sshd service is restarted
  service:
    name: sshd
    state: restarted
  tags: [common]
  
- name: JQ is present
  yum: name=jq state=latest  
  tags: [common]
  
- name: KILLALL is present
  yum: name=psmisc state=latest
  ignore_errors: yes
  tags: [common]
  
- name: Host is present
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ item.host_ip }}"
    line: "{{ item.host_ip }} {{ item.host_name }}"
  with_items: "{{ hosts }}"
  tags: [common]
 

- name: Services are not running
  service:
    name: "{{ item }}"
    state: stopped
  ignore_errors: yes
  with_items: "{{  obsolete_services }}"
  tags: [common]
